# Generated by Django 4.0.6 on 2022-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
