# Generated by Django 4.0.6 on 2022-08-22 15:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_alter_vacancy_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
