# Generated by Django 4.1 on 2022-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_rename_response_responsevacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsevacancy',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
    ]
