# Generated by Django 4.1 on 2022-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_responsevacancy_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsevacancy',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2002-04-19'),
            preserve_default=False,
        ),
    ]
