# Generated by Django 4.1 on 2022-09-19 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_remove_resume_id_alter_resume_candidate'),
        ('company', '0004_alter_company_designation'),
        ('vacancy', '0006_rename_company_id_vacancy_company'),
        ('response', '0004_responsevacancy_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponseVacancy',
            new_name='ResponseToVacancy',
        ),
        migrations.CreateModel(
            name='ResponseToCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=254, null=True)),
                ('decision', models.BooleanField(default=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.responsetovacancy')),
            ],
        ),
    ]
