# Generated by Django 4.1 on 2022-10-01 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_rename_company_id_vacancy_company'),
        ('candidate', '0003_remove_resume_id_alter_resume_candidate'),
        ('company', '0004_alter_company_designation'),
        ('response', '0005_rename_responsevacancy_responsetovacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerToCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=254, null=True)),
                ('decision', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ResponseToVacancy',
            new_name='AnswerToVacancy',
        ),
        migrations.DeleteModel(
            name='ResponseToCandidate',
        ),
        migrations.AddField(
            model_name='answertocandidate',
            name='answer_to_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.answertovacancy'),
        ),
    ]
