# Generated by Django 4.0.6 on 2022-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('COMPANY', 'Company')], default='APPLICANT', max_length=50),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
