# Generated by Django 4.0.6 on 2022-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_current_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='establishment_date',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
